package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.util.Objects;

@DynamoDBTable(tableName = "score_table")
public class Score {

  private String id;

  private String studentId;

  private String subjectId;

  private Float score;

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute(attributeName = "student_id")
  public String getStudentId() {
    return studentId;
  }

  @DynamoDBAttribute(attributeName = "subject_id")
  public String getSubjectId() {
    return subjectId;
  }

  @DynamoDBAttribute(attributeName = "score")
  public Float getScore() {
    return score;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setStudentId(String studentId) {
    this.studentId = studentId;
  }

  public void setSubjectId(String subjectId) {
    this.subjectId = subjectId;
  }

  public void setScore(Float score) {
    this.score = score;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Score score1 = (Score) o;
    return Objects.equals(studentId, score1.studentId) && Objects.equals(
        subjectId, score1.subjectId) && Objects.equals(score, score1.score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(studentId, subjectId, score);
  }
}
