package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedTimestamp;
import java.io.Serializable;
import java.util.Date;

@DynamoDBTable(tableName = "student_table")
public class Student implements Serializable {

  private String id;

  private String userId;

  private String firstName;

  private String middleName;

  private String lastName;

  private String phone;

  private Date bDate;

  private String address;

  private Date yearOfAdminssion;

  private Integer status;

  private Date graduationYear;

  private String gmail;

  public Student() {
  }

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute(attributeName = "user_id")
  public String getUserId() {
    return userId;
  }

  @DynamoDBAttribute(attributeName = "firstname")
  public String getFirstName() {
    return firstName;
  }

  @DynamoDBAttribute(attributeName = "middlename")
  public String getMiddleName() {
    return middleName;
  }

  @DynamoDBAttribute(attributeName = "lastname")

  public String getLastName() {
    return lastName;
  }

  @DynamoDBAttribute(attributeName = "phone")

  public String getPhone() {
    return phone;
  }

  @DynamoDBAttribute(attributeName = "bdate")
  @DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS", timeZone = "UTC")

  public Date getbDate() {
    return bDate;
  }

  @DynamoDBAttribute(attributeName = "address")

  public String getAddress() {
    return address;
  }

  @DynamoDBAttribute(attributeName = "getyearofadminssion")
  @DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS", timeZone = "UTC")
  public Date getYearOfAdminssion() {
    return yearOfAdminssion;
  }

  @DynamoDBAttribute(attributeName = "status")

  public Integer getStatus() {
    return status;
  }

  @DynamoDBAttribute(attributeName = "graduationyear")
  @DynamoDBTypeConvertedTimestamp(pattern = "yyyyMMddHHmmssSSS", timeZone = "UTC")
  public Date getGraduationYear() {
    return graduationYear;
  }

  @DynamoDBAttribute(attributeName = "gmail")

  public String getGmail() {
    return gmail;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public void setbDate(Date bDate) {
    this.bDate = bDate;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public void setYearOfAdminssion(Date yearOfAdminssion) {
    this.yearOfAdminssion = yearOfAdminssion;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public void setGraduationYear(Date graduationYear) {
    this.graduationYear = graduationYear;
  }

  public void setGmail(String gmail) {
    this.gmail = gmail;
  }

  @Override
  public String toString() {
    return "Student{" +
        "id='" + id + '\'' +
        ", userId='" + userId + '\'' +
        ", firstName='" + firstName + '\'' +
        ", middleName='" + middleName + '\'' +
        ", lastName='" + lastName + '\'' +
        ", phone='" + phone + '\'' +
        ", bDate=" + bDate +
        ", address='" + address + '\'' +
        ", yearOfAdminssion=" + yearOfAdminssion +
        ", status=" + status +
        ", graduationYear=" + graduationYear +
        ", gmail='" + gmail + '\'' +
        '}';
  }
}
