package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;
import java.util.Objects;

@DynamoDBTable(tableName = "student_table")
public class Student implements Serializable {

  private String id;

  private String userId;

  private String firstName;

  private String middleName;

  private String lastName;

  private String phone;

  private String bDate;

  private String address;

  private String yearOfAdminssion;

  private Integer status;

  private String graduationYear;

  private String gmail;

  public Student() {
  }

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute(attributeName = "user_id")
  public String getUserId() {
    return userId;
  }

  @DynamoDBAttribute(attributeName = "firstname")
  public String getFirstName() {
    return firstName;
  }

  @DynamoDBAttribute(attributeName = "middlename")
  public String getMiddleName() {
    return middleName;
  }

  @DynamoDBAttribute(attributeName = "lastname")

  public String getLastName() {
    return lastName;
  }

  @DynamoDBAttribute(attributeName = "phone")

  public String getPhone() {
    return phone;
  }

  @DynamoDBAttribute(attributeName = "bdate")
  public String getbDate() {
    return bDate;
  }

  @DynamoDBAttribute(attributeName = "address")

  public String getAddress() {
    return address;
  }

  @DynamoDBAttribute(attributeName = "getyearofadminssion")
  public String getYearOfAdminssion() {
    return yearOfAdminssion;
  }

  @DynamoDBAttribute(attributeName = "status")

  public Integer getStatus() {
    return status;
  }

  @DynamoDBAttribute(attributeName = "graduationyear")
  public String getGraduationYear() {
    return graduationYear;
  }

  @DynamoDBAttribute(attributeName = "gmail")

  public String getGmail() {
    return gmail;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public void setbDate(String bDate) {
    this.bDate = bDate;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public void setYearOfAdminssion(String yearOfAdminssion) {
    this.yearOfAdminssion = yearOfAdminssion;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public void setGraduationYear(String graduationYear) {
    this.graduationYear = graduationYear;
  }

  public void setGmail(String gmail) {
    this.gmail = gmail;
  }

  @Override
  public String toString() {
    return "Student{" +
        "id='" + id + '\'' +
        ", userId='" + userId + '\'' +
        ", firstName='" + firstName + '\'' +
        ", middleName='" + middleName + '\'' +
        ", lastName='" + lastName + '\'' +
        ", phone='" + phone + '\'' +
        ", bDate=" + bDate +
        ", address='" + address + '\'' +
        ", yearOfAdminssion=" + yearOfAdminssion +
        ", status=" + status +
        ", graduationYear=" + graduationYear +
        ", gmail='" + gmail + '\'' +
        '}';
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Student student = (Student) o;
    return Objects.equals(userId, student.userId) && Objects.equals(firstName,
        student.firstName) && Objects.equals(middleName, student.middleName)
        && Objects.equals(lastName, student.lastName) && Objects.equals(phone,
        student.phone) && Objects.equals(bDate, student.bDate) && Objects.equals(
        address, student.address) && Objects.equals(yearOfAdminssion,
        student.yearOfAdminssion) && Objects.equals(status, student.status)
        && Objects.equals(graduationYear, student.graduationYear)
        && Objects.equals(gmail, student.gmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, firstName, middleName, lastName, phone, bDate, address,
        yearOfAdminssion, status, graduationYear, gmail);
  }
}
