package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import java.io.Serializable;
import java.util.Objects;

@DynamoDBTable(tableName = "teacher_table")
public class Teacher implements Serializable {

  private String id;

  private String userId;

  private String firstName;

  private String middleName;

  private String lastName;

  private String phone;

  private String bDate;

  private String address;

  private String dateJoin;

  private Integer status;

  private String gmail;

  @DynamoDBHashKey(attributeName = "id")
  @DynamoDBAutoGeneratedKey
  public String getId() {
    return id;
  }

  @DynamoDBAttribute(attributeName = "user_id")
  public String getUserId() {
    return userId;
  }

  @DynamoDBAttribute(attributeName = "firstname")
  public String getFirstName() {
    return firstName;
  }

  @DynamoDBAttribute(attributeName = "middlename")
  public String getMiddleName() {
    return middleName;
  }

  @DynamoDBAttribute(attributeName = "lastname")
  public String getLastName() {
    return lastName;
  }

  @DynamoDBAttribute(attributeName = "phone")
  public String getPhone() {
    return phone;
  }

  @DynamoDBAttribute(attributeName = "bdate")
  public String getbDate() {
    return bDate;
  }

  @DynamoDBAttribute(attributeName = "address")
  public String getAddress() {
    return address;
  }

  @DynamoDBAttribute(attributeName = "datejoin")
  public String getDateJoin() {
    return dateJoin;
  }

  @DynamoDBAttribute(attributeName = "status")
  public Integer getStatus() {
    return status;
  }

  @DynamoDBAttribute(attributeName = "gmail")
  public String getGmail() {
    return gmail;
  }

  public void setId(String id) {
    this.id = id;
  }

  public void setUserId(String userId) {
    this.userId = userId;
  }

  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }

  public void setMiddleName(String middleName) {
    this.middleName = middleName;
  }

  public void setLastName(String lastName) {
    this.lastName = lastName;
  }

  public void setPhone(String phone) {
    this.phone = phone;
  }

  public void setbDate(String bDate) {
    this.bDate = bDate;
  }

  public void setAddress(String address) {
    this.address = address;
  }

  public void setDateJoin(String dateJoin) {
    this.dateJoin = dateJoin;
  }

  public void setStatus(Integer status) {
    this.status = status;
  }

  public void setGmail(String gmail) {
    this.gmail = gmail;
  }

  @Override
  public String toString() {
    return "Teacher{" +
        "id='" + id + '\'' +
        ", userId='" + userId + '\'' +
        ", firstName='" + firstName + '\'' +
        ", middleName='" + middleName + '\'' +
        ", lastName='" + lastName + '\'' +
        ", phone='" + phone + '\'' +
        ", bDate=" + bDate +
        ", address='" + address + '\'' +
        ", dateJoin=" + dateJoin +
        ", status=" + status +
        ", gmail='" + gmail + '\'' +
        '}';
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Teacher teacher = (Teacher) o;
    return Objects.equals(id, teacher.id) && Objects.equals(userId,
        teacher.userId) && Objects.equals(firstName, teacher.firstName)
        && Objects.equals(middleName, teacher.middleName) && Objects.equals(
        lastName, teacher.lastName) && Objects.equals(phone, teacher.phone)
        && Objects.equals(bDate, teacher.bDate) && Objects.equals(address,
        teacher.address) && Objects.equals(dateJoin, teacher.dateJoin)
        && Objects.equals(status, teacher.status) && Objects.equals(gmail,
        teacher.gmail);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userId, firstName, middleName, lastName, phone, bDate, address, dateJoin,
        status, gmail);
  }
}
