service: api-student
app: student
org: longtam20015
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "roleTable", "Arn" ] }
        - { "Fn::GetAtt": [ "userTable", "Arn" ] }
        - { "Fn::GetAtt": [ "studentTable", "Arn" ] }

plugins:
  - serverless-offline
package:
  artifact: build/distributions/hello.zip
#Lambda Role

functions:
  createRole:
    handler: com.serverless.handler.RoleHandler.CreateRoleHandler
    events:
      - http:
          path: /role
          method: post


  listRole:
    handler: com.serverless.handler.RoleHandler.ListRoleHandler
    events:
      - http:
          path: /role
          method: get


  createUser:
    handler: com.serverless.handler.UserHandler.CreateUserHandler
    events:
      - http:
          path: /user
          method: post
  #Lambda Role

  #Lambda User
  listUser:
    handler: com.serverless.handler.UserHandler.ListUserHandler
    events:
      - http:
          path: /user
          method: get

  getUserByUsername:
    handler: com.serverless.handler.UserHandler.GetUserHandler
    events:
      - http:
          path: /user/{id}
          method: get

  loginUser:
    handler: com.serverless.handler.UserHandler.LoginUserHandler
    events:
      - http:
          path: /user/login
          method: post
  #Lambda User

  #Lambda Student
  createStudent:
    handler: com.serverless.handler.StudentHandler.CreateStudentHandler
    events:
      - http:
          path: /student
          method: post
  listStudent:
    handler: com.serverless.handler.StudentHandler.ListStudentHandler
    events:
      - http:
          path: /student
          method: get

  getStudent:
    handler: com.serverless.handler.StudentHandler.GetStudentHandler
    events:
      - http:
          path: /student/{id}
          method: get

  getStudentTokenHandler:
    handler: com.serverless.handler.StudentHandler.GetStudentTokenHandler
    events:
      - http:
          path: /student/token
          method: get

  updateStudent:
    handler: com.serverless.handler.StudentHandler.UpdateStudentHandler
    events:
      - http:
          path: /student
          method: put
  deleteStudentHandler:
    handler: com.serverless.handler.StudentHandler.DeleteStudentHandler
    events:
      - http:
          path: /student/{id}
          method: delete
#Lambda Student

resources:
  Resources:
    roleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: role_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    studentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: student_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1