service: api-student
app: student
org: longtam20015
frameworkVersion: '2'

provider:
  name: aws
  runtime: java8
  httpApi:
    cors: true
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": [ "roleTable", "Arn" ] }
        - { "Fn::GetAtt": [ "userTable", "Arn" ] }
        - { "Fn::GetAtt": [ "studentTable", "Arn" ] }
        - { "Fn::GetAtt": [ "teacherTable", "Arn" ] }
        - { "Fn::GetAtt": [ "subjectTable", "Arn" ] }
        - { "Fn::GetAtt": [ "groupTable", "Arn" ] }
        - { "Fn::GetAtt": [ "scoreTable", "Arn" ] }
        - { "Fn::GetAtt": [ "examTable", "Arn" ] }

plugins:
  - serverless-offline
package:
  artifact: build/distributions/hello.zip
#Lambda Role

functions:
  createRole:
    handler: com.serverless.handler.RoleHandler.CreateRoleHandler
    events:
      - http:
          path: /role
          method: post


  listRole:
    handler: com.serverless.handler.RoleHandler.ListRoleHandler
    events:
      - http:
          path: /role
          method: get


  createUser:
    handler: com.serverless.handler.UserHandler.CreateUserHandler
    events:
      - http:
          path: /user
          method: post
  #Lambda Role

  #Lambda User
  listUser:
    handler: com.serverless.handler.UserHandler.ListUserHandler
    events:
      - http:
          path: /user
          method: get

  getUserByUsername:
    handler: com.serverless.handler.UserHandler.GetUserHandler
    events:
      - http:
          path: /user/{id}
          method: get

  loginUser:
    handler: com.serverless.handler.UserHandler.LoginUserHandler
    events:
      - http:
          path: /user/login
          method: post
  #Lambda User

  #Lambda Student
  createStudent:
    handler: com.serverless.handler.StudentHandler.CreateStudentHandler
    events:
      - http:
          path: /student
          method: post
  listStudent:
    handler: com.serverless.handler.StudentHandler.ListStudentHandler
    events:
      - http:
          path: /student
          method: get

  getStudent:
    handler: com.serverless.handler.StudentHandler.GetStudentHandler
    events:
      - http:
          path: /student/{id}
          method: get

  getStudentTokenHandler:
    handler: com.serverless.handler.StudentHandler.GetStudentTokenHandler
    events:
      - http:
          path: /student/token
          method: get

  updateStudent:
    handler: com.serverless.handler.StudentHandler.UpdateStudentHandler
    events:
      - http:
          path: /student
          method: put
  deleteStudentHandler:
    handler: com.serverless.handler.StudentHandler.DeleteStudentHandler
    events:
      - http:
          path: /student/{id}
          method: delete
  #Lambda Student
  #Lambda Teacher
  createTeacher:
    handler: com.serverless.handler.TeacherHandler.CreateTeacherHandler
    events:
      - http:
          path: /teacher
          method: post

  listTeacher:
    handler: com.serverless.handler.TeacherHandler.ListTeacherHandler
    events:
      - http:
          path: /teacher
          method: get

  getTeacher:
    handler: com.serverless.handler.TeacherHandler.GetTeacherHandler
    events:
      - http:
          path: /teacher/{id}
          method: get

  getTeacherTokenHandler:
    handler: com.serverless.handler.TeacherHandler.GetTeacherTokenHandler
    events:
      - http:
          path: /teacher/token
          method: get

  deleteTeacherHandler:
    handler: com.serverless.handler.TeacherHandler.DeleteTeacherHandler
    events:
      - http:
          path: /teacher/{id}
          method: delete

  updateTeacher:
    handler: com.serverless.handler.TeacherHandler.UpdateTeacherHandler
    events:
      - http:
          path: /teacher
          method: put
  #Lambda Teacher

  #Lambda Subject
  createSubject:
    handler: com.serverless.handler.SubjectHandler.CreateSubjectHandler
    events:
      - http:
          path: /subject
          method: post

  listSubjects:
    handler: com.serverless.handler.SubjectHandler.ListSubjectHandler
    events:
      - http:
          path: /subject
          method: get

  #Lambda Subject
  #Lambda Group
  createGroup:
    handler: com.serverless.handler.GroupHandler.CreateGroupHandler
    events:
      - http:
          path: /group
          method: post

  listGroup:
    handler: com.serverless.handler.GroupHandler.ListGroupHandler
    events:
      - http:
          path: /group
          method: get

  listStudentGroups:
    handler: com.serverless.handler.GroupHandler.ListGroupStudentHandler
    events:
      - http:
          path: /liststudentgroups
          method: get

  listTeacherGroups:
    handler: com.serverless.handler.GroupHandler.ListGroupTeacherHandler
    events:
      - http:
          path: /listteachergroups
          method: get

  listTeacherGroupBySubject:
    handler: com.serverless.handler.GroupHandler.ListGroupTeacherByIdHandler
    events:
      - http:
          path: /listteachergroups/{id}
          method: get
  #Lambda Group
  #Lambda Score
  createScore:
    handler: com.serverless.handler.ScoreHandler.CreateScoreHandler
    events:
      - http:
          path: /score
          method: post

  listScore:
    handler: com.serverless.handler.ScoreHandler.ListScoreHandler
    events:
      - http:
          path: /score
          method: get

  getScore:
    handler: com.serverless.handler.ScoreHandler.GetScoreHandler
    events:
      - http:
          path: /score/{id}
          method: get

  updateScore:
    handler: com.serverless.handler.ScoreHandler.UpdateScoreHandler
    events:
      - http:
          path: /score
          method: put

  deleteScoreHandler:
    handler: com.serverless.handler.ScoreHandler.DeleteScoreHandler
    events:
      - http:
          path: /score/{id}
          method: delete
  #Lambda Score
  #Lambda Exam
  createExam:
    handler: com.serverless.handler.ExamHandler.CreateExamHandler
    events:
      - http:
          path: /exam
          method: post

  listExam:
    handler: com.serverless.handler.ExamHandler.ListExamHandler
    events:
      - http:
          path: /exam
          method: get

  getExam:
    handler: com.serverless.handler.ExamHandler.GetExamHandler
    events:
      - http:
          path: /exam/{id}
          method: get

  updateExam:
    handler: com.serverless.handler.ExamHandler.UpdateExamHandler
    events:
      - http:
          path: /exam
          method: put

  deleteExamHandler:
    handler: com.serverless.handler.ExamHandler.DeleteExamHandler
    events:
      - http:
          path: /exam/{id}
          method: delete
  #Lambda Exam
resources:
  Resources:
    roleTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: role_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: user_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    studentTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: student_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    teacherTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: teacher_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    subjectTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: subject_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    groupTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: group_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    scoreTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: score_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    examTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: exam_table
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1